<?php

namespace App\Console\Commands;

use Gettext\Generators\Po;
use Gettext\Translation;
use Illuminate\Console\Command;
use Gettext\Translations;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Str;
use Symfony\Component\Process\Process;

class UpdateVueTranslations extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'translation:vue';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Searches all vue components for translations (using $__("") syntax); compares against the existing gettext generated by translations.io and adds missing strings ready for translation';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        // ************* 1. Update placeholder PHP file with translations from Vue components

        // find all $__('') translations from vue files:
        $vueText = file_get_contents(resource_path('js/components/IndicatorHub.vue'));

        $strings = Str::of($vueText)->matchAll('/\$\_\_\([\'\"](.+)[\'\"]\)/');

        // Clear and rebuild the VueTranslationPlaceholder file
        // This ensures the file is in-sync with the translation strings in the vue components - if something is removed in a vue file, it is removed from the php placeholder too.
        file_put_contents(resource_path('lang/VueTranslationPlaceholder.php'), '<?php ');

        foreach($strings as $string) {

            file_put_contents(
                resource_path('lang/VueTranslationPlaceholder.php'),
                "t('${string}');\n",
                FILE_APPEND
            );

        }
    }
}
