---
title: "State of the Smallholder Coffee farmer: Indicator Report"
output:
  pdf_document: 
    toc: true
    number_sections: true
    toc_depth: 1
date: "`r format(Sys.time(), '%d %B %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(openxlsx)
library(kableExtra)
```

```{r}
source("IndicatorStatement.R")
source("functions.R")
Indicators <- unique(data$`Indicator code`)
```

```{r, results='asis'}
cat('\n\n<!-- -->\n\n')

cat("\n\n\\pagebreak\n")

for(i in 1:length(Indicators)){
  
 data_x <- data%>%
    filter(`Indicator code` == Indicators[i])   
 
cat("  \n#",  data_x$Indicator[1], "\n")    

cat("  \n##",  data_x$Indicator[1], ":Detail Table", "\n")  

print(kable(details_table(data_x, Indicators[i]), booktabs = TRUE) %>%
  kable_styling(full_width = TRUE)%>%
  collapse_rows())

cat('\n\n<!-- -->\n\n')

cat("  \n##",  data_x$Indicator[1], ":Value Table", "\n")  

years <- sort(unique(data_x$Year))

if(length(years)<=6){

print(kable(indicator_table(data_x, Indicators[i]), booktabs = TRUE, )%>%
  kable_styling(full_width = TRUE)%>%
  collapse_rows(columns = 1))
  
} else if(length(years) >6){
  
  a <- years[1:5]
  b <- years[6:length(years)]
  
  data_a <- filter(data_x, Year %in% a)
  data_b <- filter(data_x, Year %in% b)
  
  print(kable(indicator_table(data_a, Indicators[i]), booktabs = TRUE, )%>%
  kable_styling(full_width = TRUE)%>%
  column_spec(1:2, width = "10em")%>%
  collapse_rows(columns = 1))
  
  cat('\n\n<!-- -->\n\n')
  
  print(kable(indicator_table(data_b, Indicators[i]), booktabs = TRUE, )%>%
  kable_styling(full_width = TRUE)%>%
  column_spec(1:2, width = "10em")%>%
  collapse_rows(columns = 1))
  
}
  
cat('\n\n<!-- -->\n\n')

cat("  \n##",  data_x$Indicator[1], ":Graphs", "\n")  

print(bar_graph(data_x, Indicators[i]))

cat('\n\n<!-- -->\n\n')

definition_table <- data_x%>%
  select(Source, `Indicator definition`)%>%
  unique()

cat("  \n##",  "Definition by Source", "\n")  

print(kable(definition_table, row.names = FALSE, longtable = TRUE)%>%
  column_spec(1, width = "15em")%>%
  column_spec(2, width = "28em"))

cat('\n\n<!-- -->\n\n')

cat("\n\n\\pagebreak\n")

}
```

