---
output:
  pdf_document:
    includes:
      in_header: header.tex
    keep_tex: true
    toc_depth: 1
    latex_engine: xelatex
mainfont: Roboto
title: \textbf{\textcolor{darkgreen}{Situación de los pequeños caficultores - Informe de indicadores}}
date: \textbf{\textcolor{darkgreen}{`r format(Sys.time(), '%d %B %Y')`}}
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyfoot{}
- \fancyfoot[LO,LE]{\textbf{\textcolor{darkgreen}{Nota:}} Es posible que los valores se hayan convertido a unidades estándar, valores originales y tasas de conversión disponibles en la descarga de Excel del indicador.Es posible que los valores se hayan convertido a unidades estándar, valores originales y tasas de conversión disponibles en la descarga de Excel del indicador.}
- \fancyhead[L]{\thepage}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(openxlsx)
library(kableExtra)
library(flextable)
set_flextable_defaults(fonts_ignore=TRUE)
```

```{r}
## Load Excel file with data
source("IndicatorStatement.R")

## Reference functions
# Functions file is language specific as column headers and other label strings are hard-coded in amongst the various generate functions
source("functions_es.R")

data <- excelData

countries <- unique(data$country)

indicator_codes <- unique(data$code)

data <- data%>%
  group_by(country, year, source_name, purpose, gender, scope)%>%
  mutate(n = n())%>%
  mutate(group = ifelse(n > 1, row_number(), NA))%>%
  mutate(definition_original = ifelse(is.na(definition_original), "-", definition_original))%>%
  ungroup()
```

```{r, ft.align = 'left'}
report_characteristics(data)
```

```{=latex}
% Trigger ToC creation in LaTeX
\setcounter{tocdepth}{1}
\tableofcontents
```

```{r, results='asis', ft.align='left'}
date <- format(Sys.time(), '%m-%d-%Y')

cat("  \n##")

cat("  \n", "\\textbf{\\textcolor{darkgreen}{Cita sugerida:}}", " *Situación de los pequeños caficultores - Informe de indicadores.* Disponible en:", "  \n", "\\textcolor[HTML]{159FDA}{https://coffeesmallholder.org/es/indicators}", paste0("(Accedido: ", date, ").", "\n"))
```

```{r, results='asis', ft.align='left'}
cat('\n\n<!-- -->\n\n')

cat("\n\n\\pagebreak\n")

for(i in 1:length(indicator_codes)){

data_x <- data%>%filter(code == indicator_codes[i])

cat("  \n#", data_x$code[1], data_x$name[1], "\n")

cat("  \n##", "\\textit{\\textcolor{darkgreen}{Detalles del indicador}}", "\n")

  z <- indicator_details(data, indicator_codes[i])

  cat(knit_print(z))

cat('\n\n<!-- -->\n\n')

cat("  \n##", "\\textit{\\textcolor{darkgreen}{Gráfico del indicador}}", "\n")

  knit_print(bar_graph(data, indicator_codes[i]))

cat('\n\n<!-- -->\n\n')

cat("\n\n\\pagebreak\n")

cat("  \n##", "\\textit{\\textcolor{darkgreen}{Valores del indicador}}", "\n")

for(m in 1:length(countries)){

  data_y <- data%>%filter(code == indicator_codes[i], country == countries[m])

  if(nrow(data_y)>0){

    x <- value_table(data, indicator_codes[i], countries[m])

    cat(knit_print(x))

    cat('\n\n<!-- -->\n\n')
  }

}

cat('\n\n<!-- -->\n\n')

cat("  \n##",  "\\textit{\\textcolor{darkgreen}{Definiciones del indicador}}", "\n")

  y <- definition_table(data, indicator_codes[i])

  cat(knit_print(y))

cat('\n\n<!-- -->\n\n')

cat("\n\n\\pagebreak\n")

}
```

